
```{r}
#1.Data visualization
library(readr)
Real_estate <- read_csv("R Code/Real estate.csv")
pairs(Real_estate, main="analysis")
```

```{r} 
#2.correlation matrix
cor(Real_estate)
```

```{r}
#3.additional datapoints #by adding new group of data set for each species. 
No.415<-matrix(c(2013.321, 28.4, 394.1276, 4, 24.9738, 121.4548, 39.5), nrow=1,ncol=7)
colnames(No.415)<- c("date","age","MRT_distance","unmber_stores","latitude","longtitude","price_perunite")
new_estate<- rbind(Real_estate,No.415)
```

```{r}
#4. model selection
library(olsrr)
model=lm(price_perunite~date+age+MRT_distance+unmber_stores+latitude+longtitude,data=new_estate)
allpossible=ols_step_all_possible(model)
allpossible
plot(allpossible)

```


```{r}
Estate.res=resid(model)
plot(new_estate$price_perunite,Estate.res, ylab="Residuals", xlab="price_perunit", main="New_estate")

```


```{r}
#best subset regression

best=ols_step_best_subset(model)
best
plot(best)

#so the best number of variable should be 5?
```


```{r}
#backwards analysis

#we set up alpha=0.05

summary(model,data=new_estate)
#find the largest p-value which is longtitud that 0.79829 and larger than the alpha, and we delete it,then we have a new model and do regression analysis again
```
```{r}
model2<-lm(formula = price_perunite ~ date + age + MRT_distance + unmber_stores + latitude, data = new_estate)
summary(model2)
# There is no variable that P-value is greater than 0.05. So, the fixed function is the final function before fitted.

plot(model2)
library(car)
vif(model2)
```
```{r}
#From charts, there are several abnormal points which are row 114,221,271 and 313.
fixed_estate<-new_estate[-114,]
fixed_estate<-fixed_estate[-221,]
fixed_estate<-fixed_estate[-271,]
fixed_estate<-fixed_estate[-313,]
model3<-lm(formula = price_perunite ~ date + age + MRT_distance + unmber_stores + latitude, data = fixed_estate)
plot(model3)
vif(model3)
#Here we find another abnormal point which is row 269 in dataset fixed_estate
```

```{r}
#Here we find another abnormal point which is row 269 in dataset fixed_estate
fixed_estate<-fixed_estate[-269,]
model3<-lm(formula = price_perunite ~ date + age + MRT_distance + unmber_stores + latitude, data = fixed_estate)
plot(model3)
vif(model3)

```

```{r}
#Final conclusion
#In fixed_estate dataset, there are no outlayers. So, it is assumed to be final model
final_model<-model3
summary(final_model)
anova(final_model)
```

